# Generated by Django 4.1.4 on 2023-01-14 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kismet_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='winning_option',
        ),
    ]
