# Generated by Django 4.1.4 on 2023-01-14 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kismet_app', '0002_remove_scenario_option1_remove_scenario_option2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='scenario',
            new_name='the_scenario',
        ),
    ]
