# Generated by Django 4.2.dev20221107192353 on 2023-01-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kismet_app', '0003_choice_outcome_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='option1',
            field=models.CharField(default='add', max_length=200),
        ),
        migrations.AddField(
            model_name='scenario',
            name='option2',
            field=models.CharField(default='add', max_length=200),
        ),
        migrations.AddField(
            model_name='scenario',
            name='option3',
            field=models.CharField(default='add', max_length=200),
        ),
    ]
