# Generated by Django 4.1.4 on 2023-01-14 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kismet_app', '0005_alter_choice_the_scenario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='the_scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kismet_app.scenario'),
        ),
    ]
