# Generated by Django 4.1.4 on 2023-01-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kismet_app', '0005_auto_20230114_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
