# Generated by Django 4.2.dev20221107192353 on 2023-01-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kismet_app', '0006_alter_scenario_winning_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='description',
            field=models.TextField(),
        ),
    ]
