# Generated by Django 4.1.4 on 2023-01-15 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kismet_app', '0007_auto_20230114_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outcome',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kismet_app.scenario'),
        ),
    ]
