# Generated by Django 4.2.dev20221107192353 on 2023-01-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kismet_app', '0007_alter_scenario_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='winning_option',
        ),
        migrations.AlterField(
            model_name='scenario',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
