# Generated by Django 4.1.4 on 2023-01-15 03:31

from django.db import migrations

def load_data(apps, schema_editor):
    Scenario = apps.get_model('kismet_app', 'Scenario')
    Outcome = apps.get_model('kismet_app', 'Outcome')
    in_time_of_need = Scenario.objects.get(pk=25)
    academic_honesty = Scenario.objects.get(pk=28)
    outcome = Outcome.objects.get(pk=7)
    outcome.scenario = in_time_of_need
    outcome.level = 0
    outcome = Outcome.objects.get(pk=8)
    outcome.scenario = in_time_of_need
    outcome.level = 0
    outcome = Outcome.objects.get(pk=9)
    outcome.scenario = in_time_of_need
    outcome.level = 0
    outcome = Outcome.objects.get(pk=14)
    outcome.scenario = academic_honesty
    outcome.level = 0
    outcome = Outcome.objects.get(pk=15)
    outcome.scenario = academic_honesty
    outcome.level = 0


class Migration(migrations.Migration):

    dependencies = [
        ('kismet_app', '0009_auto_20230114_1931'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
